### ISSUE TITLE
虎皮椒微信网关问题

### ISSUE THREAD

**Issue by RemotePinee** [Panyoujies/zlianpay-faka#3]
虎皮椒微信网关用不了，得更新了，作者大大。

**Comment by Panyoujies** [comment]
好的

**Comment by Panyoujies** [comment]
https://github.com/Panyoujies/zlianpay-faka/releases/tag/2.0.2

**Comment by RemotePinee** [comment]
> https://github.com/Panyoujies/zlianpay-faka/releases/tag/2.0.2

感谢感谢，另外给个建议，邮箱回复可以加个发件人名称自定义。
